### ISSUE TITLE
Rename "node" to "aquadoggo"

### ISSUE THREAD

**Issue by adzialocha** [p2panda/node#4]
Maybe `p2panda-node`? @cafca and @sophiiistika? Would the command line application name be the same?

**edit:** coin toss "doggo" vs "aqua-doggo" decided: aquadoggo

**Comment by adzialocha** [comment]
`doggo`

**Comment by cafca** [comment]
cli: `woof` 🐶

**Comment by adzialocha** [comment]
`flipflop-aqua-doggo`

**Comment by adzialocha** [comment]
`aqua-doggo`

**Comment by adzialocha** [comment]
Aquq Doggos are also doggos btw
